# Enable NODE.js support
language: node_js
node_js:
  - "6.1"
branches:
  only:
  - master
notifications:
  email: false
  slack: ijiteam:E9Rr8nKzl9hTppiVyvYAvzsZ
env:
  global:
  - LANG="en_US.UTF-8"
